### ISSUE TITLE
Running out of space? - Shouldn't be

### ISSUE THREAD

**Issue by iq-dot** [lambci/lambci#125]
Hi guys,

Suddenly my builds are running out of space, I did a couple of du commands to check for storage and I can't see myself using up 500mb space.

Is that 500mb space just for /temp or for the whole lambda in general? If it is whole lambda in general then how much space do we actually have to play with?

Here is a link to the build report:

https://lambci-buildresults-1bh1zxi4zvigo.s3.amazonaws.com/gh/buildsuggestv/suggestv-platform/builds/584/696717ce2f8ecad407b5cb10535bc72e.html

**Comment by mhart** [comment]
I would suggest not using yarn – it uses a lot more space than you think because it stores packages in its cache as well as where you install them:

https://github.com/yarnpkg/yarn/issues/6037

If you do a `du -k /tmp` I'm pretty sure you'll see that you've run out of the 500mb.

If you can, just use npm – otherwise you might need to delete yarn's cache each time.

**Comment by mhart** [comment]
Here's the RFC to add an option for no caching to yarn – still not implemented: https://github.com/yarnpkg/rfcs/pull/53

**Comment by iq-dot** [comment]
We are a bit locked into yarn at the moment, I thought I was clearing its cache each time but perhaps not, will modify my script to clear my cache and see if that works

**Comment by mhart** [comment]
If your node_modules size is approaching 250MB, then even clearing the cache won't make a difference – it will basically fail at install time because yarn will want to write to its cache as well as node_modules, essentially doubling the amount of disk space it uses. Very annoying that they haven't added a no-cache option.

**Comment by iq-dot** [comment]
I can see that they are working on a no-cache option but seems far off as the package is too deeply intertwined with their cache, let me have a go with just npm, I will loose the version locking but currently I'm only using it for PR builds, the CI server has more resources and does use yarn

**Comment by iq-dot** [comment]
Closing as switching to NPM did resolve the issu
