### ISSUE TITLE
Spin off Lambda pkg/recipe project

### ISSUE THREAD

**Issue by mhart** [lambci/lambci#13]
Considering that we already have a git tarball for use on Lambda, and instructions for getting other software bundles to work, it might be beneficial to the community at large to create a separate repo/project for this.

At the very least, it could document recipes for getting various software packages running on Lambda – but ideally it would become a repository, potentially all hosted on S3 for fast access, where Lambda functions could download pre-packaged binaries

**Comment by twoism-dev** [comment]
This sounds great, would like to help out with this in any way I can.

**Comment by michaelbarlow7** [comment]
I'm curious as to what you did to produce that git tarball. Did you compile from source? Because I'm having trouble compiling it myself, and I'm not sure I'm doing it in a portable manner...

I've actually used your tarball myself and it works great, I just wanted to know how it was made in case I want to update the version of git. 

Thanks for your efforts so far :)

**Comment by WhiteHotLoveTiger** [comment]
I'm also interested in how to compile a static version of git that'll run in lambda. Right now, I'm having trouble with https support, despite having the `libcurl4-openssl-dev` package installed on Ubuntu.
Where is the tarball you've compiled?

**Comment by mhart** [comment]
Not going to do this now that layers are a thing. Check out https://github.com/mthenw/awesome-layers for a list
