### ISSUE TITLE
Support for node.js 12

### ISSUE THREAD

**Issue by vladoro** [lambci/lambci#133]
As lambda now support node.js 12: https://aws.amazon.com/fr/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/

It now make sense to have a new image for node.js 12.

Thanks

**Comment by mhart** [comment]
Supporting Node.js 12.x (or 10.x) requires a lot more work than previous upgrades from Node.js 6.10 to 8.10 because the underlying OS has changed – from Amazon Linux 1 to Amazon Linux 2. This means that a lot of dependencies that LambCI relies on are no longer there.

I definitely plan to update LambCI to Node.js 12.x before 8.10 becomes EOL, but there will be breaking changes. I'll likely release it as LambCI 1.0 👍
