### ISSUE TITLE
Nodejs 14 support

### ISSUE THREAD

**Issue by plimpton** [lambci/lambci#135]
Node 14 is now available so it would be great to have a build environment that would be similar to their new images https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/

**Comment by mhart** [comment]
I think you might be confusing this project (which is a CI project built on Lambda) with https://github.com/lambci/docker-lambda

**Comment by plimpton** [comment]
That's an archived project

**Comment by mhart** [comment]
That's right – AWS released official images in Nov 2020 – so there was no need for the `lambci/lambda` images anymore. I assume that's what your issue was about. You can use `public.ecr.aws/lambda/nodejs:14` for example.

If the issue is in fact about LambCI (the serverless continuous integration stack), then feel free to expand on what you mean a little.

**Comment by plimpton** [comment]
That is what I was using it for. To create a package using libraries that would be compatible for the aws lambda environment. I did find an alternative in the process. You can keep this closed
