### ISSUE TITLE
Only supported in certain AWS regions?

### ISSUE THREAD

**Issue by andrewoh531** [lambci/lambci#20]
Is the Cloudformation template only supported in the N. Virginia region? I tried running it in the Sydney region and ran into the error below but it ran fine in N. Virginia.

```
Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Comment by mhart** [comment]
Ah, that's annoying. All buckets are publicly accessible... But maybe I'll have to add the same bucket in each region? That would be really annoying.

I'll look into this tomorrow, thanks for the heads up

**Comment by mhart** [comment]
Actually, buckets are global, so I'm not quite sure how this is happening – what step exactly is this occurring on? (ie, what resource?)

**Comment by mhart** [comment]
Scratch that, it's just the console that's global – I'll try creating buckets in different regions and see if I can replicate across regions

**Comment by mhart** [comment]
Ok – have just fixed this in the latest template (which has been uploaded to the same location, so you should just be able to try again).

TBH I would recommend choosing a US region over an Aus one – just because your Lambda function will have much better proximity to GitHub's servers (and npm's, etc, etc), so your builds should be faster.

Is there any particular reason you wanted to launch in the Sydney region? Did you want to access other AWS resources there or something?

**Comment by andrewoh531** [comment]
Thanks mhart. I'm located in Sydney and so my assumption was that the Github and NPM servers would be located near here. Also potentially thinking about using LambCI for creating AWS resources though the 5 min Lambda execution time restriction may force limitations.

**Comment by hayd** [comment]
Supporting other regions would be useful where tests require connecting to other machines inside a VPC.

**Comment by mhart** [comment]
@hayd it is supported in other regions – see my comment here: https://github.com/lambci/lambci/issues/20#issuecomment-231388409
