### ISSUE TITLE
Unable to find remote helper for 'https' – when npm installing git dependencies

### ISSUE THREAD

**Issue by lielran** [lambci/lambci#28]
```
$ npm install &&  karma start --single-run --no-auto-watch
npm WARN package.json MyCompany@0.0.1 No repository field.
npm WARN package.json MyCompany@0.0.1 No license field.
npm ERR! git clone --template=/tmp/lambci/home/.npm/_git-remotes/_templates --mirror https://github.com/uberVU/Sinon.JS.git /tmp/lambci/home/.npm/_git-remotes/https-github-com-uberVU-Sinon-JS-git-5ff91d4d: Cloning into bare repository '/tmp/lambci/home/.npm/_git-remotes/https-github-com-uberVU-Sinon-JS-git-5ff91d4d'...
npm ERR! git clone --template=/tmp/lambci/home/.npm/_git-remotes/_templates --mirror https://github.com/uberVU/Sinon.JS.git /tmp/lambci/home/.npm/_git-remotes/https-github-com-uberVU-Sinon-JS-git-5ff91d4d: fatal: Unable to find remote helper for 'https'
npm ERR! Linux 4.1.19-24.31.amzn1.x86_64
npm ERR! argv "/usr/local/lib64/node-v4.3.x/bin/node" "/usr/local/lib64/node-v4.3.x/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code 128
```
locally everything works great, any ideas?

**Comment by mhart** [comment]
Interesting – those git clone commands work for me:

https://lambci-public-buildresults-e3xwlufrwb3i.s3.amazonaws.com/gh/mhart/test-ci-project/builds/101/3794306266881797e24b74c4785545b9.html

Is something modifying the PATH variable?

Is there a project I can reproduce this on?

**Comment by mhart** [comment]
Ah, I've been able to reproduce:

```
npm install https://github.com/uberVU/Sinon.JS
```

Interestingly enough, this works:

```
npm install uberVU/Sinon.JS
```

So if you can change your dependencies as a workaround, that might work.

I'm looking into it – I suspect npm must be messing with the PATH somehow because the git commands it is trying to run work normally

**Comment by mhart** [comment]
Ok, I've been able to fix this, mostly, by bundling in our own custom version of npm with the specific fix needed for this problem: https://github.com/npm/npm/pull/13358

Released as v0.9.4 – let me know if that works for you!

**Comment by mhart** [comment]
For anyone stumbling on this issue – because we bundle our own version of npm, this won't fix the problem if you're using `nave` to test a specific version of node because it will use the version of npm that comes with that version of node.

To get around it – at least, until npm fixes this bug – you'll either need should be able to specify the full path to our bundled version of npm, or install your own custom version of npm

**Comment by lielran** [comment]
👍  it works for me in v0.9.4

**Comment by jdchmiel** [comment]
(sorry this is slightly unrelated) I had this issue trying to run git in lambda to an https://repository.com url as I did not install curl.  I then tried it with an ssh://repository.com url and had a similar error about ssh, which I then bundled into my zip file, and got to the seteuid issue that I am trying to get around at the moment.  TLDR; - you might be able to get around it by choosing the ssh protpcol instead of https any where you are able to edit the urls.
