### ISSUE TITLE
Support for Terraform and Apex

### ISSUE THREAD

**Issue by akranga** [lambci/lambci#40]
We are using Terraform and Apex to do Serverless. This is an enhancement request to implement [Terraform](http://terraform.io/) script and if supported [apex.io](http://github.com/apex/apex) layout. I can create a PR if accepted.

**Comment by mhart** [comment]
Interesting idea, but I'm a bit wary of adding (and maintaining) non-standard frameworks to this – what benefits would there be over the existing CloudFormation setup?

Would it support the same sort of install and update mechanism that currently exists (with Lambda-backed custom resources)?

**Comment by akranga** [comment]
Oh shortly, Terraform from Hashicorp becomes an community standard for cloud stack provisioning and typically much more appreciated over CloudFormation. It supports not only AWS but also other cloud providers like GCE or Azure. So, in theory it can help to support LambCI by other cloud providers. + It is modular. Which means you can combine stack from different modules (slack, hipchat integration, github or code-commit etc). You probable get the idea.

Custom resources are implemented in little bit different manner. In worst case scenario Terraform can also support CloudFormation resources. If this change can be accepted I can start transforming CF to Terraform

**Comment by mhart** [comment]
@akranga sure, I know what Terraform is – and I wouldn't exactly call it a community standard yet – Ansible has certainly been around longer for example. I'm just not sure it makes sense for LambCI per se.

LambCI is a standalone system – it's not something you'd deploy in the same stack as your web apps, or whatever else you might be using Apex for – so integration isn't really important.

Anyway, if you want to create a PR, I'm interested to see what it looks like – I'm just not guaranteeing that I'll merge it in if there's only marginal benefit 😸

**Comment by akranga** [comment]
Sounds good. I am also interested is it possible to repeat your CF script in Terraform in a nice way. 

Would you also be so kind and elaborate on "marginal benefit"?

**Comment by mhart** [comment]
@akranga what that means is – if it's only a small benefit, but it's a bigger cost (in terms of maintenance, keeping it up to date, people having issues with it, etc) – then it might not be worth it.

It's a bit like if you have a JavaScript project that works on npm, and someone comes along and says, "hey, can you get this working on bower?", and then someone else comes along and says, "hey, can you get this working on jspm?" – it all seems great at the start because you're supporting multiple ecosystems – but in the long run it can become quite a burden because people have issues getting it running on bower, or you have to restrict what you can do because it's not supported, etc, etc.

**Comment by joekiller** [comment]
CFN is the way to go for this right now. IMO issue can be closed for now.

**Comment by wbotelhos** [comment]
Hi @mhart  ,

Can we give up seeing Terraform support?
