### ISSUE TITLE
deployment via LambCi

### ISSUE THREAD

**Issue by lielran** [lambci/lambci#61]
Maybe i'm missing something, but how can you do deployment via LambCi or in other words run other command/s on branch X(probably 'master')

**Comment by mhart** [comment]
There's two questions there – if you're talking about running different commands on different branches, then that's covered here: https://github.com/lambci/lambci#branch-and-pull-request-properties (just specify a different `cmd` property)

If you're talking about invoking AWS commands, to push things to S3 or update Lambda function code or whatever – then that's something you'll need to write yourself. I've debated including the AWS CLI tools in LambCI, but I think they just add too much weight (which uses up function space and slows down invocation) – you can install them yourself with `pip` as part of your build though. Or you can just write Node.js scripts that use the AWS SDK – as that's included on the Lambda runtime

**Comment by larryboymi** [comment]
I started to write my own [CLI](https://www.npmjs.com/package/aws-sdk-cli) for things necessary in deploying the lambda's... just wrote it yesterday, literally only supports an S3 copy and a CloudFormation upsert at this point. I made the CF template/params be env strings in the dynamo build config of the project. I'll probably blog about it soon since that's the thing to do.

By default the code simply does a test of the project (well an install of dependencies and then test)... what @mhart said is accurate, it's on you to decide what you want to do beyond testing... [This shell script](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/198828fffc086e85335daef0b5e7f78d69fa5ad7/deploy.sh) shows how I originally used the CLI... now I plan to refactor some of the other env vars out so that multiple project artifacts can be stored separately and start also allowing project by project IAM creation capabilities for roles/policies.

**Comment by deitch** [comment]
> If you're talking about invoking AWS commands, to push things to S3 or update Lambda function code or whatever – then that's something you'll need to write yourself

Not sure I understand. Are you saying that if, for example, I want to tell k8s (or rancher or ECS or whatever) to do an update after a successful build, then I would include whatever tools I need (either in the repo or as part of the cmd to install it), and then call that command? And all of it would be wrapped in the `cmd` property?

**Comment by deitch** [comment]
BTW @mhart , I didn't say it before, but this is pretty awesome. I really am impressed!

**Comment by larryboymi** [comment]
@deitch Whatever specific things you want to do as part of your "build" are up to you. This tool simply gives you an entry point and returns the result's return code (similar to a jenkins, etc CI would).

**Comment by deitch** [comment]
@larryboymi got it. I do think it might be useful to have a few distinct steps defined, each with its own `cmd`, e.g. `build:`, `test:`, `deploy:`, `release:`, if only to have better reporting and usage patterns. But you easily can do it in one `cmd`, of course.

**Comment by larryboymi** [comment]
Yeah a lot of the different CI's aren't set up that way either, but I can see why that'd be nice.

**Comment by mhart** [comment]
Going to close this, as deployment via `cmd` is covered
