### ISSUE TITLE
Support languages as first-class property

### ISSUE THREAD

**Issue by deitch** [lambci/lambci#66]
Can lambci support languages as a first-class property? Instead of:

```json
{
  "cmd": ". ~/init/java 1.7 && mvn install -B -V && mvn test"
}
```

We would do:

```json
{
  "language": "java:1.7",
  "cmd": "mvn install -B -V && mvn test"
}
```

Of course, it is just running `~/init/java 1.7` and then whatever is in `cmd`, but it is a cleaner interface, simplifies `cmd`, and makes it easier to understand. We also can support multiple languages by doing 

```json
{
  "language": ["java:1.7","node:7.2.1"],
}
```

**Comment by mhart** [comment]
I know other CI systems have something similar, but I've deliberately shied away from doing this for a few reasons:

1. There are no extra configuration properties to understand/document/maintain
2. Because it's imperative, it's a lot easier to debug – because you can see exactly what commands are being executed to setup your environment. Most of the frustrations ppl have with CI systems are figuring out wth is going on under the hood and trying to debug it – by making it explicit, it's a lot easier to see this – because there's no magic, it's just a script or two.
3. It keeps LambCI flexible – you can add whatever customizations you want before or after language setup, in between running tests, whatever you want – all you need to know is that there's a single cmd run. It's a lot easier to reason about without needing to figure out which step is run when, etc.
4. There's really not much gained by adding properties like this – just syntactic sugar.

So, for now, I'm -1 on adding this – if there's a compelling reason to do so in the future (ie, there are some really big use cases that this enables) – then it might be worth revisiting.

Hope that makes sense!

**Comment by deitch** [comment]
> Hope that makes sense!

Yeah, I think it does. Just different philosophies. That having been said, I suspect many others added it for that reason. Hopefully this grows big enough to have such problems! :-)

> just syntactic sugar

Hey, I like sugar!

> just syntactic sugar

technically, so is having a build step and a deployment step, etc. But it does make a lot of it easier to understand. Even if they only are a bunch of separate commands (which is what I do with travis and circle).

**Comment by mhart** [comment]
> a lot easier to understand

Well I'd haggle with you on this one too – I don't think it makes it *a lot* easier to understand – it just looks a bit neater. The thing is, by adding steps like that you need to document them and maintain them – they're not inherently understandable, how would you know what gets run in what order? That would have to be documented and it's another thing you need to learn about the tool.

Again, remember that this is totally customizable – if you don't like the way concattenating commands looks with `&&` you can write a separate script (which many large projects end up doing with any CI tool), say, `lambci.sh` in your root directory and just execute that – it could specify things however you wanted:

```
#!/bin/bash -e

./test
./build
./deploy
```

Then your `cmd` is just `./lambci.sh`

**Comment by deitch** [comment]
> Well I'd haggle with you on this one too

"You've got to haggle!" https://www.youtube.com/watch?v=1xpzyk8Uo3E :-)
