### ISSUE TITLE
Use new runtime nodejs 6.10

### ISSUE THREAD

**Issue by madmod** [lambci/lambci#76]
AWS Lambda now supports the nodejs 6.10 runtime. Updating the runtime for lambci is necessary to test functions which use the new runtime. It may be desirable to have the ability to choose the runtime as a stack parameter, or alternatively to deploy one lambda for each runtime and add this as an option in the `.lambci` file so it can be selected per-project.

**Comment by mhart** [comment]
@madmod it's not actually necessary to upgrade to test functions that use Node 6 – it's been possible to test different versions of node since LambCI's inception: https://github.com/lambci/lambci#nodejs

That said, there are other advantages to using the new runtime (like having a newer npm already installed) – so it's likely that we will look at doing this in the near future 👍

**Comment by madmod** [comment]
@mhart Awesome thanks for the quick reply.

**Comment by jakeg** [comment]
Any update on this?

My problem is that lambda instances are limited to 500mb in /tmp, but by doing `nave use 8 bash -c 'npm install && npm test'` we end up with `87M /tmp/lambci/home/.nave` which is using up 87MB of very valuable disk space, and thus I'm getting `Error: ENOSPC: no space left on device, write` :/

**Comment by jakeg** [comment]
@mhart I assume this becomes more important now that Node v4 is deprecated on AWS Lambda?

> Your AWS Account currently has one or more Lambda functions configured to use the Node.js v4.3 runtime. The Node Foundation declared End-of-Life (EOL) for Node.js v4 on April 30, 2018. As a result, this version of Node.js is no longer receiving bug fixes, security updates, or performance improvements from the Node Foundation. Per the AWS Lambda runtime support policy [2] , language runtimes that have been end-of-lifed by the supplier are deprecated in AWS Lambda. While invocations of Lambda functions configured to use Node.js v4.3 will continue to work normally, the ability to create new Lambda functions configured to use the Node.js v4.3 runtime will be disabled on July 31, 2018. Code updates to existing functions using Node.js v4.3 will be disabled on October 31, 2018. We strongly encourage you to update all your functions to a newer version of Node.js (v6.10 or v8.10) so that you continue to benefit from important security, performance, and functionality enhancements offered by the Node Foundation via more recent releases.

> Which version of Node.js should I migrate to?

> While Node.js v6.10 is available on AWS Lambda, we recommend that you migrate directly to Node.js v8.10, a newer version with improved ES6 support and other language and API improvements. The AWS Lambda programming model for Node.js v8.10 maintains backwards compatibility with previous versions to simplify portability. We recommend that you test your Lambda function to validate its behavior on the newer version of Node.js.

**Comment by jakeg** [comment]
For anyone like me who needs as much space in `/tmp` as possible by not installing `nave` (it will save you ~87mb), here's a quick howto until lambci is officially updated to the latest versions of node and npm.

You'll need to both set the lambda runtime to nodejs8.10 _and_ ensure the lambda function has a modern version of npm in it, otherwise you'll have to do `nave use 8 npm install`, and thus install nave.

- clone this repo
- remove npm as a dependency in `package.json` ([this line](https://github.com/lambci/lambci/blob/master/package.json#L28)), then run `npm i --save npm` to install the latest version of npm instead of this ancient npm v2
- run `npm run pkg:zip` to create a new zip
- go to https://console.aws.amazon.com/lambda , find your lambda function and go to it
- _Actions -> Export function -> Download deployment package_ to download the current zip, so you can upload it again if this all goes wrong!
- 'Upload' the zip you just made (which has the latest npm installed in it)
- Change the runtime to node v8.10
- 'Save'
- The new function - with the latest npm and node - should now be available
- Change your usage from eg `nave use 8 npm install && nave use 8 npm build` to `npm install && npm build`
- Profit

You may also want to add `node -v && npm -v` to the lambci command you run as a sanity check that you're on the right version now.

**Comment by mhart** [comment]
The latest version (0.10.0) uses the Node.js 8.10 runtime
